services:

  apache:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
      target: development
    container_name: todo-apache
    ports:
      - "8090:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs
 
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: development
    container_name: todo-php
    volumes:
      - ./:/var/www/html
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      XDEBUG_MODE: debug
  db:
    image: mariadb
    container_name: todo-database
    ports:
      - "3306:3306"
    volumes:
      - todo-volume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: todo
      MARIADB_USER: my-user
      MARIADB_PASSWORD: 1234

volumes:
  todo-volume: